// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDqgCtuQCTT0Nsqk_c7gJk6kUumnYXDuY',
    appId: '1:1073409069814:web:04c4dcb0fec52ab76752d7',
    messagingSenderId: '1073409069814',
    projectId: 'pill-4b162',
    authDomain: 'pill-4b162.firebaseapp.com',
    storageBucket: 'pill-4b162.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTbuOrHprHAcd8E9v9PQ6k1b4tM3p24Og',
    appId: '1:1073409069814:android:b1cb1ad9811cf6e46752d7',
    messagingSenderId: '1073409069814',
    projectId: 'pill-4b162',
    storageBucket: 'pill-4b162.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5zVy8-88El0CXibzHtuqS_ogd_bBAics',
    appId: '1:1073409069814:ios:fb3c2d0fc42105866752d7',
    messagingSenderId: '1073409069814',
    projectId: 'pill-4b162',
    storageBucket: 'pill-4b162.firebasestorage.app',
    iosBundleId: 'com.example.pills',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5zVy8-88El0CXibzHtuqS_ogd_bBAics',
    appId: '1:1073409069814:ios:fb3c2d0fc42105866752d7',
    messagingSenderId: '1073409069814',
    projectId: 'pill-4b162',
    storageBucket: 'pill-4b162.firebasestorage.app',
    iosBundleId: 'com.example.pills',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDqgCtuQCTT0Nsqk_c7gJk6kUumnYXDuY',
    appId: '1:1073409069814:web:9f8d411ca83e06db6752d7',
    messagingSenderId: '1073409069814',
    projectId: 'pill-4b162',
    authDomain: 'pill-4b162.firebaseapp.com',
    storageBucket: 'pill-4b162.firebasestorage.app',
  );
}
