// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvJsZhsMCD0D-0zOssJIt2wuvF2-BJgUs',
    appId: '1:311478071046:web:e60bb6662d18fb618b3887',
    messagingSenderId: '311478071046',
    projectId: 'pillapp-e80fa',
    authDomain: 'pillapp-e80fa.firebaseapp.com',
    storageBucket: 'pillapp-e80fa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg6HD4NUyuczo3RBzm9KusrVWgeyaBaDg',
    appId: '1:311478071046:android:f897f4aedb992b7f8b3887',
    messagingSenderId: '311478071046',
    projectId: 'pillapp-e80fa',
    storageBucket: 'pillapp-e80fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYgAHGq3e__dliwX3Mr1KMQ7AQpLaVXtg',
    appId: '1:311478071046:ios:2e2ff181e90895038b3887',
    messagingSenderId: '311478071046',
    projectId: 'pillapp-e80fa',
    storageBucket: 'pillapp-e80fa.firebasestorage.app',
    iosBundleId: 'com.example.pills',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYgAHGq3e__dliwX3Mr1KMQ7AQpLaVXtg',
    appId: '1:311478071046:ios:2e2ff181e90895038b3887',
    messagingSenderId: '311478071046',
    projectId: 'pillapp-e80fa',
    storageBucket: 'pillapp-e80fa.firebasestorage.app',
    iosBundleId: 'com.example.pills',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvJsZhsMCD0D-0zOssJIt2wuvF2-BJgUs',
    appId: '1:311478071046:web:7cd83694e2d1f4508b3887',
    messagingSenderId: '311478071046',
    projectId: 'pillapp-e80fa',
    authDomain: 'pillapp-e80fa.firebaseapp.com',
    storageBucket: 'pillapp-e80fa.firebasestorage.app',
  );
}
